// <auto-generated />
using System;
using HRAttendance.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HRAttendance.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260906144646_Init8")]
    partial class Init8
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HRAttendance.Api.Models.AppNotification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("HRAttendance.Api.Models.AttendanceRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeOnly?>("CheckIn")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("CheckOut")
                        .HasColumnType("time");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("LateMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId", "Date")
                        .IsUnique();

                    b.ToTable("AttendanceRecords");
                });

            modelBuilder.Entity("HRAttendance.Api.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("NewValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.HasIndex("Entity", "EntityId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("HRAttendance.Api.Models.CurrentYearStatistics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchSent")
                        .HasColumnType("int");

                    b.Property<int>("BranchUnderCopying")
                        .HasColumnType("int");

                    b.Property<int>("CentralAdministrations")
                        .HasColumnType("int");

                    b.Property<int>("CompletedCases")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeReportId")
                        .HasColumnType("int");

                    b.Property<int>("FollowUpCases")
                        .HasColumnType("int");

                    b.Property<int>("PendingDecision")
                        .HasColumnType("int");

                    b.Property<int>("ReceivedDuringMonth")
                        .HasColumnType("int");

                    b.Property<int>("ReceivedFromOtherProsecutions")
                        .HasColumnType("int");

                    b.Property<int>("SpatialVariableCases")
                        .HasColumnType("int");

                    b.Property<int>("TechnicalOfficeSent")
                        .HasColumnType("int");

                    b.Property<int>("TechnicalOfficeUnderCopying")
                        .HasColumnType("int");

                    b.Property<int>("TransferredFromBeginningOfYear")
                        .HasColumnType("int");

                    b.Property<int>("UnderInvestigation")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeReportId")
                        .IsUnique();

                    b.ToTable("CurrentYearStatistics");
                });

            modelBuilder.Entity("HRAttendance.Api.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GradeArabic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GradeEnglish")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("JoiningDate")
                        .HasColumnType("date");

                    b.Property<string>("NameArabic")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NameEnglish")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("NameArabic");

                    b.HasIndex("NameEnglish");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("HRAttendance.Api.Models.EmployeeReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<bool>("HasError")
                        .HasColumnType("bit");

                    b.Property<string>("LeaveReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReportId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ReportId", "EmployeeId")
                        .IsUnique();

                    b.ToTable("EmployeeReports");
                });

            modelBuilder.Entity("HRAttendance.Api.Models.Mission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Missions");
                });

            modelBuilder.Entity("HRAttendance.Api.Models.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("HRAttendance.Api.Models.PermissionRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("From")
                        .HasColumnType("time");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeOnly>("To")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("PermissionRequests");
                });

            modelBuilder.Entity("HRAttendance.Api.Models.PreviousYearStatistics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchSent")
                        .HasColumnType("int");

                    b.Property<int>("BranchUnderCopying")
                        .HasColumnType("int");

                    b.Property<int>("CentralAdministrations")
                        .HasColumnType("int");

                    b.Property<int>("CompletedCases")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeReportId")
                        .HasColumnType("int");

                    b.Property<int>("FollowUpCases")
                        .HasColumnType("int");

                    b.Property<int>("PendingDecision")
                        .HasColumnType("int");

                    b.Property<int>("SpatialVariableCases")
                        .HasColumnType("int");

                    b.Property<int>("TechnicalOfficeSent")
                        .HasColumnType("int");

                    b.Property<int>("TechnicalOfficeUnderCopying")
                        .HasColumnType("int");

                    b.Property<int>("TotalPreviousYearCases")
                        .HasColumnType("int");

                    b.Property<int>("UnderInvestigation")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeReportId")
                        .IsUnique();

                    b.ToTable("PreviousYearStatistics");
                });

            modelBuilder.Entity("HRAttendance.Api.Models.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FinalizedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FinalizedByUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsFinalized")
                        .HasColumnType("bit");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<string>("OfficeNameArabic")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("OfficeNameEnglish")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FinalizedByUserId");

                    b.HasIndex("Year", "Month");

                    b.HasIndex("Year", "Month", "OfficeNameArabic")
                        .IsUnique();

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("HRAttendance.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HRAttendance.Api.Models.UserPermission", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("UserPermissions");
                });

            modelBuilder.Entity("HRAttendance.Api.Models.AttendanceRecord", b =>
                {
                    b.HasOne("HRAttendance.Api.Models.Employee", "Employee")
                        .WithMany("AttendanceRecords")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HRAttendance.Api.Models.CurrentYearStatistics", b =>
                {
                    b.HasOne("HRAttendance.Api.Models.EmployeeReport", "EmployeeReport")
                        .WithOne("CurrentYearStatistics")
                        .HasForeignKey("HRAttendance.Api.Models.CurrentYearStatistics", "EmployeeReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmployeeReport");
                });

            modelBuilder.Entity("HRAttendance.Api.Models.EmployeeReport", b =>
                {
                    b.HasOne("HRAttendance.Api.Models.Employee", "Employee")
                        .WithMany("EmployeeReports")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HRAttendance.Api.Models.Report", "Report")
                        .WithMany("EmployeeReports")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Report");
                });

            modelBuilder.Entity("HRAttendance.Api.Models.Mission", b =>
                {
                    b.HasOne("HRAttendance.Api.Models.Employee", "Employee")
                        .WithMany("Missions")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HRAttendance.Api.Models.PermissionRequest", b =>
                {
                    b.HasOne("HRAttendance.Api.Models.Employee", "Employee")
                        .WithMany("Permissions")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HRAttendance.Api.Models.PreviousYearStatistics", b =>
                {
                    b.HasOne("HRAttendance.Api.Models.EmployeeReport", "EmployeeReport")
                        .WithOne("PreviousYearStatistics")
                        .HasForeignKey("HRAttendance.Api.Models.PreviousYearStatistics", "EmployeeReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmployeeReport");
                });

            modelBuilder.Entity("HRAttendance.Api.Models.Report", b =>
                {
                    b.HasOne("HRAttendance.Api.Models.User", "FinalizedByUser")
                        .WithMany()
                        .HasForeignKey("FinalizedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("FinalizedByUser");
                });

            modelBuilder.Entity("HRAttendance.Api.Models.UserPermission", b =>
                {
                    b.HasOne("HRAttendance.Api.Models.Permission", "Permission")
                        .WithMany("UserPermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRAttendance.Api.Models.User", "User")
                        .WithMany("UserPermissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HRAttendance.Api.Models.Employee", b =>
                {
                    b.Navigation("AttendanceRecords");

                    b.Navigation("EmployeeReports");

                    b.Navigation("Missions");

                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("HRAttendance.Api.Models.EmployeeReport", b =>
                {
                    b.Navigation("CurrentYearStatistics");

                    b.Navigation("PreviousYearStatistics");
                });

            modelBuilder.Entity("HRAttendance.Api.Models.Permission", b =>
                {
                    b.Navigation("UserPermissions");
                });

            modelBuilder.Entity("HRAttendance.Api.Models.Report", b =>
                {
                    b.Navigation("EmployeeReports");
                });

            modelBuilder.Entity("HRAttendance.Api.Models.User", b =>
                {
                    b.Navigation("UserPermissions");
                });
#pragma warning restore 612, 618
        }
    }
}
